# Finding Arsenal a New Left Back

The statistics that we will be focussing on:

- Touches in Att 3rd
- Progressive Passes Received
- Progressive Carries
- Key Passes
- Crosses into Penalty Area
- Carries into Penalty Area
- Successful Take-Ons

## Data Loading

In [53]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler

# Creating a connection to database, selecting all rows from VIEW created to select relevant stats from DF players with >10.0 90s. Storing results in dataframe.
conn = sqlite3.connect(r"C:\Users\Owner\dev\23_24_player_stats\data\23_24_player_stats.db")
cursor = conn.cursor()
cursor.execute("SELECT * FROM DF_WIDE_OUTLET")
rows = cursor.fetchall()
column_names = [description[0] for description in cursor.description]
df = pd.DataFrame(rows, columns=column_names)
print(df)
conn.close()

                Player    Pos   Age           Squad  total_90s    KP  \
0    Aaron Wan-Bissaka     DF  25.0  Manchester Utd       19.8  0.61
1         Aarón Martín     DF  26.0           Genoa       15.3  1.70
2         Abakar Sylla     DF  20.0      Strasbourg       19.9  0.25
3          Abdel Abqar     DF  24.0          Alavés       25.7  0.12
4          Abdul Mumin     DF  25.0  Rayo Vallecano       18.8  0.21
..                 ...    ...   ...             ...        ...   ...
688        Álex Moreno     DF  30.0     Aston Villa       11.5  0.96
689        Álex Suárez     DF  30.0      Las Palmas       28.5  0.21
690     Édgar González  DF,MF  26.0         Almería       28.0  0.25
691     Óscar Mingueza  DF,MF  24.0      Celta Vigo       33.3  1.44
692    Óscar de Marcos     DF  34.0   Athletic Club       25.1  0.84

     ProgCarries  ProgPasRec  TouAtt3rd  SuccTkOn  CrossPA  PassPA  CarPA
0           1.52        2.73      14.00      0.86     0.15    0.81   0.20
1           1.83        4.71      16.70      0.39     0.72    1.05   0.20
2           0.40        0.10       2.81      0.45     0.00    0.20   0.00
3           0.27        0.04       1.63      0.12     0.00    0.08   0.00
4           0.32        0.21       1.33      0.11     0.00    0.21   0.00
..           ...         ...        ...       ...      ...     ...    ...
688         2.78        7.22      18.50      1.30     0.17    1.13   0.87
689         0.42        0.53       4.63      0.39     0.11    0.28   0.00
690         0.21        0.21       2.39      0.25     0.04    0.11   0.00
691         2.22        4.02      21.10      1.08     0.51    1.65   0.27
692         2.03        4.98      21.10      0.24     1.04    1.47   0.24

[693 rows x 13 columns]

## Data Pre-processing

In [54]:
# Printing summary statistics, and number of nulls to see whether null handling is necessary.
display(df.describe())
print(df.isnull().sum())

,Age,total_90s,KP,ProgCarries,ProgPasRec,TouAtt3rd,SuccTkOn,CrossPA,PassPA,CarPA
count,693.000000,693.000000,693.000000,693.000000,693.000000,693.000000,693.000000,693.000000,693.000000,693.000000
mean,26.034632,21.309380,0.676609,1.455267,2.600188,10.977229,0.534791,0.263506,0.659437,0.216061
std,4.036175,7.006996,0.576631,1.139662,2.725368,8.540006,0.530271,0.309296,0.567288,0.324504
min,16.000000,10.100000,0.000000,0.000000,0.000000,0.790000,0.000000,0.000000,0.000000,0.000000
25%,23.000000,15.400000,0.230000,0.610000,0.270000,3.320000,0.170000,0.000000,0.190000,0.000000
50%,26.000000,20.500000,0.520000,1.160000,1.560000,9.650000,0.370000,0.140000,0.530000,0.080000
75%,29.000000,26.700000,0.940000,2.060000,4.430000,16.600000,0.750000,0.430000,0.990000,0.280000
max,39.000000,38.000000,3.410000,7.400000,18.880000,64.300000,4.150000,2.470000,3.290000,2.920000

Player         0
Pos            0
Age            0
Squad          0
total_90s      0
KP             0
ProgCarries    0
ProgPasRec     0
TouAtt3rd      0
SuccTkOn       0
CrossPA        0
PassPA         0
CarPA          0
dtype: int64

## Exploratory Data Analysis

In [63]:
# Metrics to be scaled
metrics = ['KP', 'ProgCarries', 'ProgPasRec', 'TouAtt3rd', 'SuccTkOn', 'CrossPA', 'PassPA', 'CarPA']

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Normalize the metrics
df[metrics] = scaler.fit_transform(df[metrics])

# Calculate the average score for each player
df['AverageScore'] = df[metrics].mean(axis=1)

# List of left-footed players
left_footed_players = ['Javi Galán', 'Sergio Reguilón', 'Quentin Merlin', 'Alfie Doughty', 'Alfonso Pedraza', 'Álex Grimaldo',
                       'David Raum', 'Andrew Robertson', 'Sergio Akieme', 'Raphaël Guerreiro', 'Josh Doig', 'Alejandro Balde', 'Alphonso Davies']

# Filter the DataFrame to include only left-footed players
left_footed_df = df[df['Player'].isin(left_footed_players)]

# Display the filtered DataFrame
display(left_footed_df)

,Player,Pos,Age,Squad,total_90s,KP,ProgCarries,ProgPasRec,TouAtt3rd,SuccTkOn,CrossPA,PassPA,CarPA,AverageScore
21,Alejandro Balde,DF,19.0,Barcelona,15.3,0.249267,0.644595,0.488347,0.382774,0.315663,0.186235,0.398176,0.448630,0.389211
31,Alfie Doughty,DF,23.0,Luton Town,32.5,0.630499,0.390541,0.267479,0.384349,0.245783,0.299595,0.401216,0.294521,0.364248
33,Alfonso Pedraza,DF,27.0,Villarreal,12.4,0.472141,0.610811,0.414195,0.269406,0.195181,0.457490,0.589666,0.277397,0.410786
35,Alphonso Davies,DF,22.0,Bayern Munich,22.9,0.475073,0.713514,0.321504,0.371752,0.737349,0.125506,0.410334,0.523973,0.459876
45,Andrew Robertson,DF,29.0,Liverpool,18.8,0.967742,0.452703,0.365996,0.445757,0.065060,0.259109,0.419453,0.109589,0.385676
150,David Raum,DF,25.0,RB Leipzig,30.4,0.656891,0.341892,0.428496,0.404818,0.142169,0.453441,0.620061,0.167808,0.401947
289,Javi Galán,DF,28.0,Atlético Madrid,12.9,0.832845,0.928378,1.000000,1.000000,0.845783,0.744939,0.990881,0.143836,0.810833
327,Josh Doig,DF,21.0,Hellas Verona,24.1,0.434018,0.609459,0.286547,0.382774,0.327711,0.364372,0.346505,0.157534,0.363615
555,Quentin Merlin,DF,21.0,Marseille,22.1,0.821114,0.581081,0.610169,0.595339,0.291566,0.538462,0.945289,0.294521,0.584693
561,Raphaël Guerreiro,"DF,MF",29.0,Bayern Munich,13.2,0.510264,0.368919,0.361229,0.474099,0.236145,0.275304,0.598784,0.130137,0.369360
606,Sergio Akieme,DF,25.0,Almería,27.7,0.460411,0.493243,0.403072,0.376476,0.484337,0.352227,0.361702,0.150685,0.385269
608,Sergio Reguilón,DF,26.0,Manchester Utd,17.0,0.982405,0.693243,0.608581,0.807904,0.409639,0.599190,0.680851,0.202055,0.622983
687,Álex Grimaldo,DF,27.0,Leverkusen,30.9,0.739003,0.336486,0.447564,0.554401,0.156627,0.287449,0.699088,0.167808,0.423553